CREATE TABLE Games (
    Game_ID INT AUTO_INCREMENT PRIMARY KEY,

    Game_Code VARCHAR(30) NOT NULL UNIQUE COMMENT '系統代碼',
    Game_Name VARCHAR(100) NOT NULL COMMENT '遊戲名稱',

    Game_Icon VARCHAR(255) DEFAULT NULL COMMENT '遊戲圖示',

    Status ENUM('啟用','停用') DEFAULT '啟用',

    Sort_Order INT DEFAULT 0,

    Create_Time DATETIME DEFAULT CURRENT_TIMESTAMP,
    Update_Time DATETIME DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);